server:
  port: 8889
index: 'index'
maxAgeResources: 0
database:
  web: mongodb://localhost:27017/web
  admin: mongodb://localhost:27017/adming
bigscreenChannel: 'http://localhost:8085'
frontendConfig:
  projectorUrl: 'http://localhost:8888'
